### ISSUE TITLE
Tree table is not working with Mendix 9.1 

### ISSUE THREAD

**Issue by cerego** [JelteMX/mendix-tree-table#34]
The page is not working after the Mendix 9.1 installation. The page displays the following message: An error occurred in a "com.mendix.widget.custom.mxtreetable.MxTreeTable" widget. Check updates for the widget in the Mendix App Store or contact the widget developer.

The javascript error is the following:
TypeError: window.mx.meta.getEntity(...).isPersistable is not a function
at t.getMXValidations (MxTreeTable.js?637555872077119955:3)

The issue seems due to mendix-react-widget-utils and specifically the entityIsPersistable function.

**Comment by JelteMX** [comment]
Thanks for reporting, I will look into it

**Comment by JelteMX** [comment]
Fixed in [2.3.1](https://github.com/JelteMX/mendix-tree-table/releases/tag/2.3.1) and updated in the AppStore
